version: '3.8'

services:
  postgres:
    container_name: my_ps
    image: postgres:latest
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: mm
      POSTGRES_DB: my_db
      PGDATA: /pgdata
    volumes:
       - /home/illia/Final_Project/Demo/pgdata:/pgdata
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql


    ports:
      - "5431:5432"
    networks:
      - default
    restart: always

  admirer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080