"""Added Images to Cvs

Revision ID: 7a5b5c0549a7
Revises: 7ccc75f8f93c
Create Date: 2022-05-20 12:15:31.820078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5b5c0549a7'
down_revision = '7ccc75f8f93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('cv_id', sa.Integer(), nullable=True))
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'CVs', ['cv_id'], ['id'])
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'])
    op.drop_column('images', 'cv_id')
    # ### end Alembic commands ###
