"""Added Images

Revision ID: 7ccc75f8f93c
Revises: 2ba8d80901f5
Create Date: 2022-05-19 22:03:59.660967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccc75f8f93c'
down_revision = '2ba8d80901f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###
